name: test
on:
  pull_request:
    paths-ignore:
      - 'website/**'

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 20
          packageManager: yarn

      - name: Build Packages
        run: yarn build

      - name: Setup K6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Start Benchmark
        working-directory: ./benchmark
        run: |
          yarn test
        env:
          NODE_NO_WARNINGS: true
          NODE_ENV: production
          GITHUB_PR: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
