name: lint-prettier

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 20
      - name: Prettier Check
        run: yarn prettier:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Setup env
        uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 20
      - name: ESLint
        run: yarn lint
